image: gitpod/workspace-go
tasks:
  - init: go mod tidy  
  - name: Start acceptance environment
    command: make testacc-up
    openMode: split-right
# Port 8080 is used for acceptance testing, and we don't need to option it when the container comes up
ports:
  - port: 8080
    onOpen: ignore
vscode:
    extensions:
        - golang.Go