name: 🐞 Bug Report
description: File a bug report
labels: ["bug", "needs-triage"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Hi there 👋,

        Thank you for reporting the bug! Completing all sections of this form will help us find a solution quickly.

        If the problem is a missing feature, then please use a [Feature Request](https://github.com/gitlabhq/terraform-provider-gitlab/issues/new?template=FEATURE_REQUEST.yml) instead.
  - type: input
    id: provider-version
    attributes:
      label: GitLab Provider version
      description: What version of the `gitlabhq/gitlab` provider are you using? (This is usually found in any `terraform` command output.)
      placeholder: "X.X.X"
    validations:
      required: false
  - type: input
    id: gitlab-version
    attributes:
      label: GitLab version
      description: What version and edition of GitLab are you using? (This can be found in the "Help" section in GitLab.)
      placeholder: "GitLab XXXXX Edition X.X"
    validations:
      required: false
  - type: input
    id: terraform-version
    attributes:
      label: Terraform version
      description: What version of terraform are you using?
      placeholder: "Please paste the output of `terraform -v` here"
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Relevant Terraform Configuration
      description: Please copy and paste the relevant Terraform Configuration here. This will be automatically formatted into code, so no need for backticks.
      render: hcl
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: problem-description
    attributes:
      label: Description
      description: |
        Please describe the problem you are experiencing and what you would have expected to see.
        Make sure to include important factoids or special steps someones needs to reproduce the issue.
    validations:
      required: false
