name: ✨ Feature Request
description: Request a new feature
labels: ["enhancement", "needs-triage"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Hi there 👋,

        Thank you for requesting a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please describe your feature ideas in as much detail as possible, including an example configuration.
    validations:
      required: true
  - type: checkboxes
    id: contribution-willingness
    attributes:
      label: Do you want to implement this?
      options:
        - label: I would like to implement this myself 👷
          required: false
