# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: issue-comment-created

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            stale
            waiting-response
