# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Automated handling of stale issues and pull requests.
#
# NOTE: When changing "days-before-*" values, please also update the "stale-issue-message" and/or
# "stale-pr-message" values.

name: stale

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        * * * * *
    - cron: '8 3 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          stale-issue-message: |
            Marking this issue as stale due to 90 days of inactivity. This helps our maintainers find and focus on the active issues. If this issue receives no comments in the next 14 days it will automatically be closed. Maintainers can also remove the `stale` label.
            If this issue was automatically closed and you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!
          stale-pr-message: |
            Marking this pull request as stale due to 30 days of inactivity. This helps our maintainers find and focus on the active pull requests. If this pull request receives no comments in the next 14 days it will automatically be closed. Maintainers can also remove the `stale` label.
            If this pull request was automatically closed and you feel this pull request should be reopened, we encourage creating a new pull request linking back to this one for added context. Thank you!
          close-issue-message: 'This issue was closed because it has been stale for 14 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 14 days with no activity.'
          days-before-issue-stale: 90
          days-before-pr-stale: 30
          days-before-issue-close: 14
          days-before-pr-close: 14
          exempt-issue-labels: keep-open,bug,enhancement
